[package]
name = "codecrafters-interpreter"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
regex = { version = "1.11.1" }
thiserror = { version = "1.0.38" }
